# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Twitok' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Twitok
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'IQKeyboardManagerSwift'
  pod 'FirebaseDatabase'
  pod 'FirebaseStorage'
  pod 'KeychainSwift', '~> 20.0'
  
end
